spring:
  application:
    name: product-service
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  datasource:
    url: jdbc:postgresql://localhost:5432/msa_exam
    username: root
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    defer-datasource-initiallization: true
    show-sql: true
  sql:
      init:
        mode: always
server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
