spring:
  application:
    name: auth
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  datasource:
    url: jdbc:postgresql://localhost:5432/msa_exam
    username: root
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    #    defer-datasource-initiallization: true
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 19095
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
