server:
  port: 19091  # 게이트웨이 서비스가 실행될 포트 번호

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway의 라우팅 설정
        - id: order  # Order 서비스 라우팅
          uri: lb://order  # Eureka를 통해 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/**  # /order/** 경로로 들어오는 요청 처리

        - id: product  # Product 서비스 라우팅
          uri: http://localhost:19093  # Eureka를 통해 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/**  # /product/** 경로로 들어오는 요청 처리
#          filters:
#            - Weight=product-group,70  # 70% 요청 비중 설정

        - id: product-alt  # Product 서비스 대체 라우팅
          uri: http://localhost:19094  # Eureka를 통해 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/**  # /product/** 경로로 들어오는 요청 처리
#          filters:
#            - Weight=product-group,30  # 30% 요청 비중 설정

        - id: auth # Auth 서비스 라우팅
          uri: http://localhost:19095  # Eureka를 통해 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/auth/**  # /auth/** 경로로 들어오는 요청 처리

      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버의 URL을 지정


service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"